# Generated by Django 2.1.7 on 2019-04-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdizBlog', '0003_post_deneme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_max',
        ),
    ]
