# Generated by Django 2.1.7 on 2019-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdizBlog', '0004_auto_20190421_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.BinaryField()),
                ('m2', models.BooleanField()),
                ('m3', models.DurationField()),
                ('m4', models.PositiveSmallIntegerField()),
                ('m5', models.SlugField()),
                ('m6', models.UUIDField()),
            ],
        ),
    ]
