# Generated by Django 2.2 on 2019-04-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdizBlog', '0005_alanlar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author1',
        ),
    ]
